export default {
  enter: 'enter',
  reject: 'reject',
  wasOnWallet: 'wasOnWallet',
  savedOrders: 'savedOrders',
  deletedOrders: 'deletedOrders',
  didAllWidgetsDataSend: 'didAllWidgetsDataSend',
  activeTabId: 'activeTabId',
  testnetSkip: 'testnetSkip',
  storageRevision: '_revision',
  wasCautionPassed: 'wasCautionPassed',
  hiddenCoinsList: 'hiddenCoinsList',
  privateKeysSaved: 'privateKeysSaved',
  demoMoneyReceived: 'demoMoneyReceived',
  wasOnExchange: 'wasOnExchange',
  didOpenSignUpModal: 'didOpenSignUpModal',
  lastCheckBalance: 'lastCheckBalance',
}
